### ISSUE TITLE
Error when a blank line is in the middle of a VCARD

### ISSUE THREAD

**Issue by fabiomux** [schmurfy/vcard_parser#5]
I got a malformed error (line 53 field.rb) while parsing a vcf file exported by my Android smartphone, seems that a blank line after the last line of the PHOTO field introduce this error, but really any scenario like these below raise an error:

```
BEGIN:VCARD
FN: ...
<blank line>
TEL: ...
END:VCARD
```

```
BEGIN:VCARD
FN: ...
TEL: ...
<blank line>
END:VCARD
```

Instead this one gives no error:

```
BEGIN:VCARD
<blank line>
FN: ...
TEL: ...
END:VCARD
```

**Comment by schmurfy** [comment]
I just release 1.0.0 which should fix your issue :)

(I bumped to 1.0.0 since it is pretty much stable, I use it and it works well)

**Comment by fabiomux** [comment]
Thank you Julien, it works great!
